Repository bounswe/bounswe2019group5, pull requests merged in 2019-05, with the labels that each got.

#58 Query Wikidata
  practice-app/libs/create-exercise.js
  practice-app/libs/getDataFromOxfordApi.js
  practice-app/package.json
Labels: Backend, Effort: High, New Feature, Status: Review Needed

#63 Database connection
  .DS_Store
  .gitignore
  practice-app/libs/connectToDatabase.js
Labels: Backend, Effort: Low, New Feature, Priority: Medium, Status: Review Needed

#70 naive frontend implementation
  frontend/.gitignore
  frontend/README.md
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/DataCacher.js
  frontend/src/ExercisePage/ExercisePage.js
  frontend/src/HomePage/HomePage.js
  frontend/src/ResultPage/ResultPage.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/serviceWorker.js
  frontend/yarn.lock
Labels: Effort: High, Frontend, Priority: Critical, Status: Review Needed

#69 result json example for backend
  practice-app/app.js
Labels: Effort: High, Frontend, Priority: Critical, Status: Review Needed

#71 non integrated
  .gitignore
  practice-app/app.js
  practice-app/frontend/.gitignore
  practice-app/frontend/README.md
  practice-app/frontend/package-lock.json
  practice-app/frontend/package.json
  practice-app/frontend/public/favicon.ico
  practice-app/frontend/public/index.html
  practice-app/frontend/src/App.css
  practice-app/frontend/src/App.js
  practice-app/frontend/src/App.test.js
  practice-app/frontend/src/DataCacher.js
  practice-app/frontend/src/ExercisePage/ExercisePage.js
  practice-app/frontend/src/HomePage/HomePage.js
  practice-app/frontend/src/ResultPage/ResultPage.js
  practice-app/frontend/src/index.css
  practice-app/frontend/src/index.js
  practice-app/frontend/src/serviceWorker.js
  practice-app/frontend/yarn.lock
  practice-app/package-lock.json
Labels: Bug Fix, Effort: High, Priority: Critical, Status: In Progress

#72 Integration
  practice-app/app.js
  practice-app/frontend/public/index.html
  practice-app/libs/create-exercise.js
Labels: Backend, Effort: High, Priority: Critical, Status: Review Needed

#77 Create exercise
  .DS_Store
  .gitignore
  practice-app/app.js
  practice-app/libs/checkExercise.js
  practice-app/libs/create-exercise.js
  practice-app/libs/getDatafromWikiData.js
  practice-app/package-lock.json
Labels: Backend, Effort: High, Frontend, Priority: High, Status: Review Needed

#102 Randomize create exercise and test
  practice-app/app.js
  practice-app/frontend/src/App.js
  practice-app/libs/create-exercise.js
  practice-app/package-lock.json
  practice-app/package.json
  practice-app/test/test.js
Labels: Backend, New Feature

#98 General classes
  practice-app/app.js
  practice-app/generalClasses.txt
  practice-app/libs/getGeneralClasses.js
Labels: Backend, Bug Fix, Effort: Low, New Feature, Priority: High, Status: Review Needed

#104 Give informative feedback after exercise
  practice-app/frontend/package-lock.json
  practice-app/frontend/src/ResultPage/ResultPage.js
  practice-app/libs/checkExercise.js
  practice-app/package-lock.json
  practice-app/package.json
  practice-app/test/test_for_checkExercise.js
Labels: Backend, New Feature

#105 added tests for genereateRenderedArray() function
  practice-app/libs/checkExercise.js
  practice-app/test/testGenerateRenderedArray.js
Labels: Backend, Effort: Medium, Priority: High, Type: Test
